### ISSUE TITLE
IMAP Error

### ISSUE THREAD

**Issue by adelorenzo** [ramarav/Bitmex_bot#1]
Hello,

Thank you for your script. I get an error message when I run it:

**=== ERROR ON ACCOUNT: _email@email.com_ : list index out of range**

What could this mean? I don't use gmail. Thank you!

**Comment by ramarav** [comment]
Hi @adelorenzo 
I used gmail in my code by writing **_`smtp_server: 'imap.gmail.com'`_** in yaml file.
You need to change it accordingly if you are not using gmail.

**Comment by venkiiee** [comment]
@adelorenzo : did you fix the error? are you running the bot ?
